---
- name: Create a sandbox instance
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    keypair: NOC-Staging_Ansible
    instance_type: t2.micro
    image: ami-1853ac65
    region: us-east-1
  tasks:
    - name: Launch instance
      ec2:
         key_name: "{{ keypair }}"
         group: default
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         instance_tags:
            Name: Ansible-Demo
         aws_access_key: XXXXXXXX
         aws_secret_key: XXXXXXXX
      register: ec2
    - name: Print all ec2 variables
      debug: var=ec2


